# server: the default configuration for a contestServer

spring:
    application.name: pivotable-server
    graphql:
        graphiql:
            enabled: true

springdoc.show-actuator: true

management:
  endpoint:
    health:
      show-details: always