name: JS Integration (Playwright) Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    # Package the server to serve API and JS
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Install Adhoc Server
      # `install` so that each module is available in local repository, as later mvn command will not be executed on the root
      run: mvn install -Pfast -pl :pivotable-server -am
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install NPM dependencies
      working-directory: ./pivotable/js
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./pivotable/js
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./pivotable/js
      run: npm run pw_localhost8080
    - uses: actions/upload-artifact@v6
      if: always()
      with:
        name: playwright-report
        path: pivotable/js/playwright-report/
        retention-days: 30
